language: php

git:
  depth: 3

env:
  global:
    - APPLICATION_ENV=devtest
    - APPLICATION_STORE=DE
    - PROJECT=suite

matrix:
  fast_finish: true
  include:
    - php: "7.3"
      dist: xenial

    - name: Just pip
      php: "7.3"
      dist: xenial
      install:
        - google-chrome-stable --version
        - chromedriver --version
        - pip3 install --user pipenv
        - pipenv --python 3 install -r requirements.txt
      before_script:
        - nvm install 8
      script:
        - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
        - pipenv run robot -d Results robotframework-tests/Tests/User_Journeys/Demo_Script.robot

    - name: Robot Framework Tests
      php: "7.3"
      dist: xenial
      install:
        - chmod -R a+x config/Shared/ci/travis/
        - composer install --optimize-autoloader --no-interaction
        - config/Shared/ci/travis/install_elasticsearch.sh
        - config/Shared/ci/travis/install_mailcatcher.sh
        - chromedriver --version
        - pip3 install --user pipenv
        - pipenv --python 3 install -r requirements.txt
      script:
        #- git clone git@github.com:spryker/robotframework-sandbox.git --branch dev --single-branch --depth 1 robotframework-tests
        - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
        - pipenv --python 3 run robot -d Results robotframework-tests/Tests/User_Journeys/Demo_Script.robot

addons:
  chrome: stable
  postgresql: 9.6
  apt:
    packages:
      - graphviz
      - chromium-chromedriver
      - build-essential
      - libpq-dev
      - libssl-dev
      - openssl
      - libffi-dev
      - zlib1g-dev
      - python3-pip
      - python3-dev
      - rabbitmq-server
  hosts:
    - zed.de.spryker.test
    - www.de.spryker.test

cache:
  directories:
    - $HOME/.composer/cache
    - /home/travis/.rvm/gems # Mailcatcher is a ruby gem, takes 5 minutes to install.
    - ./node_modules

services:
  - postgresql
  - redis

sudo: required

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv config-rm xdebug.ini
  - composer global require hirak/prestissimo
  - ( awk '1;/@hook travis-ci/{exit}' config/Shared/stores.php ; awk 'NR>1' config/Shared/ci/travis/stores.php ; awk '/@hook travis-ci/,0' config/Shared/stores.php ) > config/Shared/stores_tmp.php ; mv config/Shared/stores_tmp.php config/Shared/stores.php

install:
  - chmod -R a+x config/Shared/ci/travis/
  - composer install --optimize-autoloader --no-interaction
  - config/Shared/ci/travis/install_elasticsearch.sh
  - config/Shared/ci/travis/install_mailcatcher.sh

before_script:
  - nvm install 8

  - mkdir -p shared/data/common/jenkins
  - mkdir -p shared/data/common/jenkins/jobs
  - mkdir -p data/DE/cache/Yves/twig -m 0777
  - mkdir -p data/DE/cache/Zed/twig -m 0777
  - mkdir -p data/DE/logs -m 0777
  - chmod -R 777 data/
  - chmod -R 660 config/Zed/dev_only_private.key
  - chmod -R 660 config/Zed/dev_only_public.key

  - cat config/Shared/ci/travis/postgresql_ci.config >> config/Shared/ci/travis/config_ci.php

  - cp config/Shared/ci/travis/config_ci.php config/Shared/config_local.php

  - config/Shared/ci/travis/acceptance_env.sh
  - vendor/bin/install DE -r testing -v

script:
  - vendor/bin/codecept run -g Presentation


notifications:
  email: false
